events/config/routes.rb
Rails.application.routes.draw do
  # top
  root 'welcome#index'
  # login
  get "/auth/:provider/callback" => "sessions#create"
  # logout
  delete "/logout" => "sessions#destroy"
  resources :events
end

events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

events/app/models/event.rb
class Event < ApplicationRecord
    validates :name, length: { maximum: 50 }, presence: true
    validates :place, length: { maximum: 100 }, presence: true
    validates :content, length: { maximum: 2000 }, presence: true
    validates :start_at, presence: true
    validates :end_at, presence: true
    validate :start_at_should_be_before_end_at

    private

    def start_at_should_be_before_end_at
        return unless start_at && end_at
        if start_at >= end_at
            errors.add(:start_at, "は終了時間よりも前に設定してください")
        end
    end
end

events/app/models/user.rb
class User < ApplicationRecord
    # モデル名以外を関連名(created_events)を指定したのでclass_nameを指定する。
    # 外部キーもデフォルトのuser_idでないのでforeign_keyで指定する。
    has_many :created_events, class_name: "Event", foreign_key: "owner_id"

    # <Hashie::Array []> raw_info=#<OmniAuth::AuthHash avatar_url="https://avatars.githubusercontent.com/u/72182214?v=4" bio=nil blog="" company=nil created_at="2020-10-01T04:25:20Z" email=nil events_url="https://api.github.com/users/zabrak002/events{/privacy}" followers=0 followers_url="https://api.github.com/users/zabrak002/followers" following=0 following_url="https://api.github.com/users/zabrak002/following{/other_user}" gists_url="https://api.github.com/users/zabrak002/gists{/gist_id}" gravatar_id="" hireable=nil html_url="https://github.com/zabrak002" id=72182214 location=nil login="zabrak002" name=nil node_id="MDQ6VXNlcjcyMTgyMjE0" organizations_url="https://api.github.com/users/zabrak002/orgs" public_gists=0 public_repos=4 received_events_url="https://api.github.com/users/zabrak002/received_events" repos_url="https://api.github.com/users/zabrak002/repos" site_admin=false starred_url="https://api.github.com/users/zabrak002/starred{/owner}{/repo}" subscriptions_url="https://api.github.com/users/zabrak002/subscriptions" twitter_username=nil type="User" updated_at="2022-05-27T02:35:41Z" url="https://api.github.com/users/zabrak002"> scope=""> info=#<OmniAuth::AuthHash::InfoHash email=nil image="https://avatars.githubusercontent.com/u/72182214?v=4" name=nil nickname="zabrak002" urls=#<OmniAuth::AuthHash Blog="" GitHub="https://github.com/zabrak002">> provider="github" uid="72182214">
    # User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."provider" = ? AND "users"."uid" IS NULL LIMIT ?  [["provider", "github"], ["LIMIT", 1]]
    def self.find_or_create_from_auth_hash!(auth_hash)
        Rails.logger.info(auth_hash)
        provider = auth_hash[:provider]
        uid = auth_hash[:uid]
        nickname = auth_hash[:info][:nickname]
        image_url = auth_hash[:info][:image]

        # providerとuidでunique
        User.find_or_create_by!(provider: provider, uid: uid) do |user|
            user.name = nickname
            user.image_url = image_url
        end
    end
end

events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate
    helper_method :logged_in?, :current_user

    private

    def logged_in?
        !!current_user
    end

    def current_user
        return unless session[:user_id]
        @current_user || User.find(session[:user_id])
    end

    def authenticate
        return if logged_in?
        redirect_to root_path, alert: "ログインしてください"
    end
end

events/app/controllers/events_controller.rb
class EventsController < ApplicationController
    def new
        @event = current_user.created_events.build
    end

    def create
        @event = current_user.created_events.build(event_params)

        if @event.save
            # インスタンス変数を引数とするとroutes.rbのresourcesで生成されたshowにルーティングされる
            # user GET    /users/:id(.:format)           users#show
            redirect_to @event, notice: "作成しました"
        end
    end

    private

    def event_params
        params.require(:event).permit(:name, :place, :content, :start_at, :end_at)
    end
end

events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authenticate, only: :create

    # ログイン状態にする
    def create
        # OmniAuth::AuthHash Githubから渡されたログイン情報やOAuthのアクセストークン
        user = User.find_or_create_from_auth_hash!(request.env["omniauth.auth"])
        # ログイン状態にする
        session[:user_id] = user.id
        # セッションに格納されrequestごとにリセットされる特殊なメッセージ
        redirect_to root_path, notice: 'ログインしました'
    end

    # ログアウト状態にする
    def destroy
        reset_session
        redirect_to root_path, notice: "ログアウトしました"
    end
end

events/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
  end
end

events/app/helpers/application_helper.rb
module ApplicationHelper
end

events/app/helpers/events_helper.rb
module EventsHelper
end

events/app/helpers/sessions_helper.rb
module SessionsHelper
end

events/app/helpers/welcome_helper.rb
module WelcomeHelper
end

events/app/views/application/_errors.html.haml
.alert.alert-danger
    %ul.mb-0
        - errors.full_messages.each do |message|
            %li = message

events/app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"

events/app/views/events/new.html.haml
- now = Time.zone.now

%h1.mt-2 イベント作成

= form_with(model: @event, class: "form-horizontal") do |f|
    #errors
    .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
    .form-group
        = f.label :place
        = f.text_field :place, class: "form-control"
    .form-group
        = f.label :start_at
        %div
            = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
    .form-group
        = f.label :end_at
        %div
            = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
    .form-group
        = f.label :content
        = f.text_area :content, class: "form-control", row: 10
    = f.submit class: "btn btn-primary"

events/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Events
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-dark
      .container
        = link_to "Awesome Events", root_path, class: "navbar-brand text-white-50 mr-auto"
        %ul.navbar-nav
          %li.nav-item
            = link_to "イベントを作る", new_event_path, class: "nav-link text-white-50"
          - if logged_in?
            %li.nav-item
              = link_to "ログアウト", logout_path, class: "nav-link text-white-50", method: :delete
          - else
            %li.nav-item
              = link_to "GitHubでログイン", '/auth/github', class: "nav-link text-white-50", method: :post
    .container
      - if flash.notice
        .alert.alert-success
          = flash.notice
      - if flash.alert
        .alert.alert-danger
          = flash.alert
      = yield

events/app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml